# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       Eldorado-Workshop
email:       'info@impresso-project.ch'
description: 'The Eldorado workshop, supported by the impresso project, will bring together a group of historians, librarians, computer scientists and designers to discuss how digitisation is changing historical research practices.'
baseurl:     '/eldorado' # The subpath of your site, e.g. /blog
url:         'https://impresso.github.io' # The base hostname & protocol for your site
twitter:     'https://twitter.com/impressoproject'
github:      'https://github.com/impresso/eldorado'


markdown:  kramdown
permalink: pretty
paginate:  10
paginate_path: /blog/page:num/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
